[SPARK-LLAP-48] Support `--packages` (#56)
## What changes were proposed in this pull request?

Up to now, `spark-llap` can be used with `--jars`, but fails on `--packages`.
This PR aims to support `--packages` by cleaning up the dependencies.

```
$ spark-shell --packages com.hortonworks:spark-llap_2-11:1.0.2-2.1 --repositories http://repo.hortonworks.com/content/groups/public
scala> sql("show tables").show
17/01/31 00:31:38 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.RuntimeException: Stream '/jars/org.apache.curator_apache-curator-2.7.1.jar' was not found.
```

## How was this patch tested?

After publishing to Maven, use `--packages` option.

This close #48 .
(cherry picked from commit 3a7c361db783b290f598dc7f39ef48434a30c95c)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>