[SPARK-LLAP-30] `DROP PARTITION` should work without HDFS privilege (#33)
## What changes were proposed in this pull request?

Currently, `ALTER TABLE ... DROP PARTITION` fails with the following errors when the user doesn't have a enough HDFS privilege to change `hive` warehouse directory. When Spark Thrift Server is running as `hive`, this is not a problem. Also, this is not about permission issue. After correct authorization, this situation happens.

```
[alter_drop_partiton_3_t_alter] dongjoon ALTER TABLE t_alter_part DROP PARTITION (c=1)
Error: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Got exception: java.io.IOException Failed to move to trash:
hdfs://.../apps/hive/warehouse/spark_ranger_test.db/t_alter_part/c=1; (state=,code=0)
```

## How was this patch tested?

For example, run Spark Thrift Server in a normal user account without `HDFS` privilege, and
execute `ALTER TABLE ... DROP PARTITION` statement.

Note that the test script contains user id `spark`. To run the test script with non-`spark` user, both test script and answer files should be fixed manually.

This closes #32 .
(cherry picked from commit fc1adbb2b6b3097edfe90ed77306682af3d1b8aa)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>