[SPARK-LLAP-12] `CREATE TABLE` should be blocked properly according to the access rule (#15)
Currently, `Spark-LLAP` always creates tables without considering Ranger access rule while Hive does not.

**SPARK-LLAP**
```sql
$ beeline -u jdbc:hive2://localhost:10016 -n spark -e 'create table t(a int)'
...
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.707 seconds)
Beeline version 1.2.1000.2.5.3.0-37 by Apache Hive
Closing: 0: jdbc:hive2://localhost:10016
```

**HIVE**
```sql
$ beeline -u jdbc:hive2://localhost:10500 -n spark -e 'create table t(a int)'
...
Error: Error while compiling statement: FAILED: HiveAccessControlException Permission denied: user [spark] does not have [CREATE] privilege on [default/t] (state=42000,code=40000)
Closing: 0: jdbc:hive2://localhost:10500
```

This closes #12.
(cherry picked from commit 9a4f7aa8c0b38ea9a38e1446d5dc152d88c4610e)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>